modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20All%20Loot%20Drops"
logoFile="icon.png"

[[mods]]
modId="alllootdrops"
version="3.6"
displayName="All Loot Drops"
displayURL="https://serilum.com/mod/all-loot-drops"
authors="Rick South"
description='''Entities always drop all their possible loot in a configurable amount.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

akanealw, Alister, Andrean Olgo, aternosorg, Cherriesaurus, MWS, t128, Tyler Behl, XAgent, ตัวตรึง พระนคร   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.alllootdrops]]
    modId="collective"
    mandatory=true
    versionRange="[8.16,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.alllootdrops]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.1.1]"
    ordering="NONE"
    side="BOTH"
